// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCX7ChEz0g8HPENDeuBCWhf2R4AniaDCw',
    appId: '1:894071181361:web:dcbc344914a07e40478510',
    messagingSenderId: '894071181361',
    projectId: 'malenia-400d7',
    authDomain: 'malenia-400d7.firebaseapp.com',
    storageBucket: 'malenia-400d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSHVUL8fXn-4bC1PgxP_geyuRm3GIi-U',
    appId: '1:894071181361:android:27fc0b406b649d7b478510',
    messagingSenderId: '894071181361',
    projectId: 'malenia-400d7',
    storageBucket: 'malenia-400d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNfSJNDM1wbqxKSWedbMf0Okp8tCsxyY',
    appId: '1:894071181361:ios:2b24bca4ecf67a09478510',
    messagingSenderId: '894071181361',
    projectId: 'malenia-400d7',
    storageBucket: 'malenia-400d7.appspot.com',
    iosBundleId: 'com.example.pushDrive',
  );
}
